# serverless.yml

component: scf  # (必选) 组件名称，在该实例中为scf
name: request_test # 必选) 组件实例名称.
org: "1254105469" # (可选) 用于记录组织信息，默认值为您的腾讯云账户 appid
app: request_test # (可选) 用于记录组织信息. 默认与name相同.
stage: dev # (可选) 用于区分环境信息，默认值是 dev

inputs:
    name: request_test2  #云函数名称
    namespace: default #云函数命名空间
    role: #云函数执行角色
    enableRoleAuth: true #赋予SCF 相关的角色权限，默认true
     # 1. 默认写法，新建特定命名的 cos bucket 并上传
    src: ./src
    # 2. src 为对象，并且制定忽略上传文件夹 node_modules
    # src:
    #   src: ./src
    #   exclude:
    #     - 'node_modules/**'
    # 3. 指定 bucket name 和文件的方式，直接上传 cos 中的文件部署云函数
    # src:
    #    bucket: tinatest   # bucket name，当前会默认在bucket name后增加 appid 后缀, e.g. bucketname-appid
    #    key: 'code.zip'      # bucket key 指定存储桶内的文件
    # 4. 指定本地文件到 bucket
    # src:
    #   bucket: tinatest   # bucket name
    #   src:         # 指定本地路径
    handler: index.main_handler #入口
    runtime: Nodejs10.15 #运行环境
    region: ap-guangzhou #函数所在区域
    description: request请求测试
    memorySize: 128 #内存大小，单位MB
    timeout: 20  #超时时间，单位秒
    environment: # 环境变量
      variables: # 环境变量对象
        TEST: value
    vpcConfig:  #私有网络配置
      subnetId: "subnet-4sr71o2i" #私有网络的Id
      vpcId: "vpc-qeyd3d6t" #子网ID
    #deadLetter: #死信队列配置
    #  type: 
    #  name: 
    #  filterType: deadLetterFilterType
    layers:
      - name: request    # layer名称
        version: 1           # 版本
    #cls: 	//函数日志
    #  logsetId: ClsLogsetId
    #  topicId: ClsTopicId
    eip: false #是否开启固定IP
    #tags:
    #  key1: value1
    #  key2: value2 # tags 的key value
    events: #触发器
    #  - timer: #定时触发器
    #      name: timer
    #      parameters:
    #        cronExpression: '*/5 * * * *' #每5秒触发一次
    #        enable: true
    #        argument: argument # 额外的参数
      - apigw: #api网关触发器
          name: teemo_serverless
          parameters:
            serviceId: service-qfee7m5m
            protocols:
              - http
            description: the serverless service
            environment: test
            endpoints:
              - path: /request_test2
                method: ANY
                apiId: 
                description: Serverless REST API
                enableCORS: FALSE
                responseType: HTML
                serviceTimeout: 10
                param:
                #  - name: request_test1
                #    position: PATH
                #    required: 'TRUE'
                #    type: string
                #    defaultValue: abc
                #    desc: mytest
                #  - name: cde
                #    position: PATH
                #    required: 'TRUE'
                #    type: string
                #    defaultValue: abc
                #    desc: mytest
                function:
                  isIntegratedResponse: FALSE
                  functionQualifier: $LATEST
                #usagePlan:
                #  usagePlanId: 1111
                #  usagePlanName: slscmp
                #  usagePlanDesc: sls create
                #  maxRequestNum: 1000
                #auth:
                #  serviceTimeout: 15
                #  secretName: secret
                #  secretIds:
                #    - AKIDNSdvdFcJ8GJ9th6qeZH0ll8r7dE6HHaSuchJ
     # - apigw:
     #     name: serverless_test
     #     parameters:
     #       serviceId: service-cyjmc4eg
     #       protocols:
     #         - http
     #       description: the serverless service
     #       environment: release
     #       endpoints:
     #         - path: /users
     #           method: POST
     # - cos: //cos触发器
     #     name: cli-appid.cos.ap-beijing.myqcloud.com
     #     parameters:
     #       bucket: cli-appid.cos.ap-beijing.myqcloud.com
     #       filter:
     #         prefix: filterdir/
     #         suffix: .jpg
     #       events: cos:ObjectCreated:*
     #       enable: true
     # - cmq: //CMQ Topic 触发器
     #     name: cmq_trigger
     #     parameters:
     #       name: test-topic-queue
     #       enable: true
     # - ckafka://ckafka触发器
     #     name: ckafka_trigger
     #     parameters:
     #       name: ckafka-2o10hua5
     #       topic: test
     #       maxMsgNum: 999
     #       offset: latest
     #       enable: true
